/*
Copyright (c) 2001 Peter Dimov and Multi Media Ltd.
Copyright (c) 2016 Modified Work Barrett Adair

Distributed under the Boost Software License, Version 1.0.
(See accompanying file LICENSE.md or copy at http://boost.org/LICENSE_1_0.txt)

HEADER GUARDS INTENTIONALLY OMITTED
DO NOT INCLUDE THIS HEADER DIRECTLY

*/

#undef CALLABLE_TRAITS_INCLUDE_QUALIFIERS
#undef CALLABLE_TRAITS_INCLUDE_ABOMINABLE_QUALIFIERS


#define CALLABLE_TRAITS_INCLUDE_QUALIFIERS
#define CALLABLE_TRAITS_INCLUDE_ABOMINABLE_QUALIFIERS
#include <callable_traits/detail/unguarded/pmf_2.hpp>
#undef CALLABLE_TRAITS_INCLUDE_QUALIFIERS
#undef CALLABLE_TRAITS_INCLUDE_ABOMINABLE_QUALIFIERS

#define CALLABLE_TRAITS_INCLUDE_QUALIFIERS const
#define CALLABLE_TRAITS_INCLUDE_ABOMINABLE_QUALIFIERS CALLABLE_TRAITS_ABOMINABLE_CONST
#include <callable_traits/detail/unguarded/pmf_2.hpp>
#undef CALLABLE_TRAITS_INCLUDE_QUALIFIERS
#undef CALLABLE_TRAITS_INCLUDE_ABOMINABLE_QUALIFIERS

#define CALLABLE_TRAITS_INCLUDE_QUALIFIERS volatile
#define CALLABLE_TRAITS_INCLUDE_ABOMINABLE_QUALIFIERS CALLABLE_TRAITS_ABOMINABLE_VOLATILE
#include <callable_traits/detail/unguarded/pmf_2.hpp>
#undef CALLABLE_TRAITS_INCLUDE_QUALIFIERS
#undef CALLABLE_TRAITS_INCLUDE_ABOMINABLE_QUALIFIERS

#define CALLABLE_TRAITS_INCLUDE_QUALIFIERS const volatile
#define CALLABLE_TRAITS_INCLUDE_ABOMINABLE_QUALIFIERS CALLABLE_TRAITS_ABOMINABLE_CONST CALLABLE_TRAITS_ABOMINABLE_VOLATILE
#include <callable_traits/detail/unguarded/pmf_2.hpp>
#undef CALLABLE_TRAITS_INCLUDE_QUALIFIERS
#undef CALLABLE_TRAITS_INCLUDE_ABOMINABLE_QUALIFIERS

#ifndef CALLABLE_TRAITS_DISABLE_REFERENCE_QUALIFIERS

#define CALLABLE_TRAITS_INCLUDE_QUALIFIERS &
#define CALLABLE_TRAITS_INCLUDE_ABOMINABLE_QUALIFIERS &
#include <callable_traits/detail/unguarded/pmf_2.hpp>
#undef CALLABLE_TRAITS_INCLUDE_QUALIFIERS
#undef CALLABLE_TRAITS_INCLUDE_ABOMINABLE_QUALIFIERS

#define CALLABLE_TRAITS_INCLUDE_QUALIFIERS &&
#define CALLABLE_TRAITS_INCLUDE_ABOMINABLE_QUALIFIERS &&
#include <callable_traits/detail/unguarded/pmf_2.hpp>
#undef CALLABLE_TRAITS_INCLUDE_QUALIFIERS
#undef CALLABLE_TRAITS_INCLUDE_ABOMINABLE_QUALIFIERS

#define CALLABLE_TRAITS_INCLUDE_QUALIFIERS const &
#define CALLABLE_TRAITS_INCLUDE_ABOMINABLE_QUALIFIERS const &
#include <callable_traits/detail/unguarded/pmf_2.hpp>
#undef CALLABLE_TRAITS_INCLUDE_QUALIFIERS
#undef CALLABLE_TRAITS_INCLUDE_ABOMINABLE_QUALIFIERS

#define CALLABLE_TRAITS_INCLUDE_QUALIFIERS volatile &
#define CALLABLE_TRAITS_INCLUDE_ABOMINABLE_QUALIFIERS volatile &
#include <callable_traits/detail/unguarded/pmf_2.hpp>
#undef CALLABLE_TRAITS_INCLUDE_QUALIFIERS
#undef CALLABLE_TRAITS_INCLUDE_ABOMINABLE_QUALIFIERS

#define CALLABLE_TRAITS_INCLUDE_QUALIFIERS const volatile &
#define CALLABLE_TRAITS_INCLUDE_ABOMINABLE_QUALIFIERS const volatile &
#include <callable_traits/detail/unguarded/pmf_2.hpp>
#undef CALLABLE_TRAITS_INCLUDE_QUALIFIERS
#undef CALLABLE_TRAITS_INCLUDE_ABOMINABLE_QUALIFIERS

#define CALLABLE_TRAITS_INCLUDE_QUALIFIERS const &&
#define CALLABLE_TRAITS_INCLUDE_ABOMINABLE_QUALIFIERS const &&
#include <callable_traits/detail/unguarded/pmf_2.hpp>
#undef CALLABLE_TRAITS_INCLUDE_QUALIFIERS
#undef CALLABLE_TRAITS_INCLUDE_ABOMINABLE_QUALIFIERS

#define CALLABLE_TRAITS_INCLUDE_QUALIFIERS volatile &&
#define CALLABLE_TRAITS_INCLUDE_ABOMINABLE_QUALIFIERS volatile &&
#include <callable_traits/detail/unguarded/pmf_2.hpp>
#undef CALLABLE_TRAITS_INCLUDE_QUALIFIERS
#undef CALLABLE_TRAITS_INCLUDE_ABOMINABLE_QUALIFIERS

#define CALLABLE_TRAITS_INCLUDE_QUALIFIERS const volatile &&
#define CALLABLE_TRAITS_INCLUDE_ABOMINABLE_QUALIFIERS const volatile &&
#include <callable_traits/detail/unguarded/pmf_2.hpp>
#undef CALLABLE_TRAITS_INCLUDE_QUALIFIERS
#undef CALLABLE_TRAITS_INCLUDE_ABOMINABLE_QUALIFIERS

#endif //#ifndef CALLABLE_TRAITS_DISABLE_REFERENCE_QUALIFIERS
